# This Kubernetes manifest deploys Jaeger and a sample application (Hotrod) that sends traces to Jaeger without using OTEL
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  selector:
    app: jaeger
  ports:
    - name: ui
      port: 16686
      targetPort: 16686
      protocol: TCP
    - name: agent-udp
      port: 6831
      targetPort: 6831
      protocol: UDP
    - name: collector
      port: 14268
      targetPort: 14268
      protocol: TCP
    - name: zipkin
      port: 9411
      targetPort: 9411
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.47
          ports:
            - containerPort: 16686 # UI
              protocol: TCP
            - containerPort: 14268 # Collector HTTP
              protocol: TCP
            - containerPort: 6831  # Agent UDP
              protocol: UDP
            - containerPort: 9411  # Zipkin
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: hotrod
spec:
  selector:
    app: hotrod
  ports:
    - name: web
      port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotrod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotrod
  template:
    metadata:
      labels:
        app: hotrod
    spec:
      containers:
        - name: hotrod
          image: jaegertracing/example-hotrod:1.47
          args: ["all"]
          env:
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              value: "http://jaeger:14268/api/traces"
          ports:
            - containerPort: 8080
              protocol: TCP
