apiVersion: batch/v1
kind: Job
metadata:
  name: send-mock-trace
  namespace: default
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: send-trace
          image: send-trace:local


